name: Deploy to Server
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: NextJs Cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', 'app/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nextjs-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: |
          yarn build
      - name: Package Build
        run: |
          ls -al .next/
          cp public  .next/standalone -r
          cp .next/static .next/standalone/.next -r
          cp Procfile .next/standalone
          PACKAGE_DIR=./.next/standalone/ node prune-package.js
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./.next/standalone
          include-hidden-files: true

  # deploy-test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: Test
  #   steps:
  #     - name: Download Build Artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build
  #         path: ./.next/standalone

  #     - name: Setup Deployment Environment
  #       run: |
  #         mkdir -p ~/.ssh
  #         ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
  #         chmod 600 id_rsa
  #     - name: Send Build to Server
  #       run: |
  #         rsync -Pav --no-perms --omit-dir-times --delete -e "ssh -i id_rsa" .next/standalone/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}" --exclude='.next/standalone/cache' --exclude='.next/cache'
  #     - name: Restart Agpb
  #       run: |
  #         # echo ${{ vars.ENVIRONMENT }}
  #         ssh -i id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cd ${{ secrets.SSH_REMOTE_PATH }} && pm2 restart ecosystem.config.js --update-env"
  #     - name: Remove SSH Private Key
  #       if: always()
  #       run: rm -f id_rsa

  deploy-toolforge:
    runs-on: ubuntu-latest
    needs: build
    environment: Toolforge
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./.next/standalone
      - name: Setup Deployment Environment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
          chmod 600 id_ed25519
      - name: Push to Distribution branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: ./.next/standalone/ # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
      - name: Restart Agpb
        run: |
          ssh -i id_ed25519 "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" <<'EOF'
            become agpb
            toolforge build start git@github.com:${{ secrets.MY_GITHUB_USER }}/${{ github.repository }} --ref build --use-latest-versions
            toolforge webservice buildservice restart --mount all
            exit
            exit
          EOF
